In [33]:
import duckdb
import pandas as pd
import ast

In [34]:
# Connect to DuckDB (creates a file-based DB)
con = duckdb.connect("/home/leloc/Document/USTH/Thesis/Data/translation.db")

print(con.execute("SELECT * FROM translations LIMIT 5").fetchdf())

                                  thai  \
0                    - รร.แกรนด์โฮเต็ล
1                         - สายไม่ว่าง
2                         นั่นใครพูดคะ
3  ฉันจะโอนสายคุณ ไปที่แผนกรูมเซอร์วิส
4                              ฮัลโหลๆ

                                              viet  \
0                               - Khách sạn Grand.
1                                 - Đường dây bận.
2                                          Ai đấy?
3  Tôi có thể kết nối quý khách với dịch vụ phòng.
4                                            A lô.

                                      thai_input_ids  \
0  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
1  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
2  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
3  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
4  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...

                                 thai_attention_mask  \
0  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
1  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
2  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
3  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
4  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...

                                        vi_input_ids  \
0  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
1  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
2  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
3  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
4  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...

                                   vi_attention_mask
0  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
1  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
2  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
3  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
4  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...

In [35]:
tables = con.execute("SHOW TABLES").fetchall()
print(tables)

[('tokenized_batches',), ('translations',)]

In [36]:
df = con.execute("SELECT thai_input_ids, vi_input_ids FROM translations LIMIT 10").fetchdf()
print(df.head())

                                      thai_input_ids  \
0  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
1  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
2  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
3  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...
4  [128, 4, 149, 228, 1, 0, 0, 0, 0, 0, 0, 140, 2...

                                        vi_input_ids
0  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
1  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
2  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
3  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...
4  [128, 4, 149, 196, 1, 0, 0, 0, 0, 0, 0, 140, 2...

In [37]:
print(df.dtypes)

thai_input_ids    object
vi_input_ids      object
dtype: object

In [38]:
import pickle

# Hàm để giải mã pickle (từ byte sang list token)
def decode_pickle_data(x):
    try:
        return pickle.loads(x)
    except Exception as e:
        print("Lỗi giải mã pickle:", e)
        return []

# Giải mã pickle thành list
df["thai_input_ids"] = df["thai_input_ids"].apply(decode_pickle_data)
df["vi_input_ids"] = df["vi_input_ids"].apply(decode_pickle_data)

# Định nghĩa padding token (thường là 0 và 1)
PADDING_IDS = {0, 1}

# Tính độ dài thật sự (không tính padding)
df["thai_true_len"] = df["thai_input_ids"].apply(lambda x: len([t for t in x if t not in PADDING_IDS]))
df["viet_true_len"] = df["vi_input_ids"].apply(lambda x: len([t for t in x if t not in PADDING_IDS]))

# Tính độ dài toàn bộ chuỗi token (bao gồm padding)
df['thai_token_len'] = df['thai_input_ids'].apply(len)
df['viet_token_len'] = df['vi_input_ids'].apply(len)

# In ra so sánh
print(df[['thai_token_len', 'thai_true_len', 'viet_token_len', 'viet_true_len']])

   thai_token_len  thai_true_len  viet_token_len  viet_true_len
0              43             15              39              7
1              43              7              39              8
2              43              6              39              5
3              43             17              39             14
4              43              7              39              5
5              43             32              39             21
6              43             19              39             21
7              43             12              39             12
8              43             22              39             16
9              43              7              39             10

In [6]:
import pandas as pd
df = pd.read_csv('/home/leloc/Document/USTH/Thesis/Data/preprocessed_with_split.csv')
df

,Thai,Viet,split
0,ฉันรู้ว่าคุณเคยบอกว่า จะคอยส่งข่าวฉันเรื่อยๆ แ...,Tôi biết bà đã nói sẽ báo cho tôi nhưng tuần n...,train
1,เคียว ฉันก็มี มีด ฉันก็มี ดูของฉันซะก่อน,Đủ loại đặc thù nhé Có lưỡi hái tử thần Lưỡi h...,train
2,แดเนียล เลอรอย แม็คแคบบี้ ที่ 3 สามีฉันเอง,Chắc cậu có nghe nói đến anh ấy Anh ấy phát mi...,train
3,แพร์รี่ มันยุค 90 นะ ใครสนล่ะ,Thập niên 90 rồi ai quan tâm nữa,train
4,เธ เธฑเธ เธ เน เธฐ เธ เน เธฒเธ เน เธญเธขเธฒเธ ...,Nhìn xem tôi cũng muốn rời khỏi đây Thật đấy,train
...,...,...,...
339109,ผู้พันมาร์ควิสเผาทหาร 47 คนทั้งเป็น เพื่อให้นิ...,Để trả lời câu hỏi của ông John Ruth khi Thiếu...,test
339110,บูลส์จบฤดูกาลด้วยสถิติชนะ 72 ครั้ง แพ้สิบครั้ง...,Đội Bulls kết thúc mùa giải với hiệu số thắng ...,test
339111,สตาลินกราดถูกสร้างขึ้นบนตลิ่ง ข้างแม่น้ำวอลก้า...,Stalingrag được xây dựng trên những ngọn đồi n...,test
339112,9834 And then I say bo add a B 9834 9834,chữ cái đầu tiên của cái tên,test
339113,ดูเหมือนว่าวิสัยทัศน์ของท่านส ส ชา จะเคยเข้ากั...,Vậy tôi đoán tầm nhìn của ông đã tương hỗ với ...,test

In [11]:
import pandas as pd
import re

def is_thai_with_numbers(text):
    if not isinstance(text, str):
        return False
    # Cho phép ký tự tiếng Thái, số, khoảng trắng, dấu .,!? và dấu -
    pattern = r'^[\u0e00-\u0e7f0-9 .,!?-]+$'
    return bool(re.fullmatch(pattern, text))

# Giả sử df là DataFrame của bạn với cột 'Thai'
non_thai_rows = df[~df['Thai'].apply(is_thai_with_numbers)]

print("Các dòng không phải tiếng Thái (cho phép số):")
print(non_thai_rows)

Các dòng không phải tiếng Thái (cho phép số):
                                                     Thai  \
9       สัญญาณอันตราย Leonard Sheldon หนีไปแล้ว พับผ่า...
24                  we killed all these animals ourselves
32             A Taste of Armageddon ซีซันหนึ่ง ตอนที่ 23
35             Compensating for audio deIay Just a second
40                             Let s just get it done man
...                                                   ...
339075                      I wish I was the moon tonight
339076                     So some of you are still human
339095  ลายเซ็นสเปกตรัมของ Tucana II เผยให้เห็นดวงดาวข...
339104  cause it wouldn t do my career prospects too m...
339112           9834 And then I say bo add a B 9834 9834

                                                     Viet  split
9       Nó thực sự là một quá trình khá đơn giản em th...  train
24      Cám ơn chúng tôi đã tự mình săn bắn những con ...  train
32                     A Taste of Armageddon Mùa 1 tập 23  train
35      Tôi cần người hiểu được tổng thể vụ án này nói...  train
40                              Hãy hành động nào các bạn  train
...                                                   ...    ...
339075                 Anh chỉ muốn làm ánh trăng đêm nay   test
339076                 Để đấy tôi Anh làm cái quái gì vậy   test
339095  Dấu hiệu quang phổ Tucana II cho thấy các ngôi...   test
339104  vì nó không có lợi gì cho nghề nghiệp của tôi đâu   test
339112                       chữ cái đầu tiên của cái tên   test

[32482 rows x 3 columns]

In [13]:
# Giữ lại các dòng hợp lệ: tiếng Thái + số + khoảng trắng + .,!? thôi
df = df[df['Thai'].apply(is_thai_with_numbers)].reset_index(drop=True)
df

,Thai,Viet,split
0,ฉันรู้ว่าคุณเคยบอกว่า จะคอยส่งข่าวฉันเรื่อยๆ แ...,Tôi biết bà đã nói sẽ báo cho tôi nhưng tuần n...,train
1,เคียว ฉันก็มี มีด ฉันก็มี ดูของฉันซะก่อน,Đủ loại đặc thù nhé Có lưỡi hái tử thần Lưỡi h...,train
2,แดเนียล เลอรอย แม็คแคบบี้ ที่ 3 สามีฉันเอง,Chắc cậu có nghe nói đến anh ấy Anh ấy phát mi...,train
3,แพร์รี่ มันยุค 90 นะ ใครสนล่ะ,Thập niên 90 rồi ai quan tâm nữa,train
4,เธ เธฑเธ เธ เน เธฐ เธ เน เธฒเธ เน เธญเธขเธฒเธ ...,Nhìn xem tôi cũng muốn rời khỏi đây Thật đấy,train
...,...,...,...
306627,แต่ตอนนี้เขาได้เห็นแล้ว ว่ากระทั่งฮิมเลอร์ ก็พ...,Ông ta chợt nhớ ra viên thuốc độc mà ông ta dà...,test
306628,ผู้พันมาร์ควิสเผาทหาร 47 คนทั้งเป็น เพื่อให้นิ...,Để trả lời câu hỏi của ông John Ruth khi Thiếu...,test
306629,บูลส์จบฤดูกาลด้วยสถิติชนะ 72 ครั้ง แพ้สิบครั้ง...,Đội Bulls kết thúc mùa giải với hiệu số thắng ...,test
306630,สตาลินกราดถูกสร้างขึ้นบนตลิ่ง ข้างแม่น้ำวอลก้า...,Stalingrag được xây dựng trên những ngọn đồi n...,test
306631,ดูเหมือนว่าวิสัยทัศน์ของท่านส ส ชา จะเคยเข้ากั...,Vậy tôi đoán tầm nhìn của ông đã tương hỗ với ...,test

In [1]:
from transformers import AutoTokenizer

# Tải tokenizer của NLLB-200 1.3B
tokenizer = AutoTokenizer.from_pretrained("facebook/nllb-200-distilled-600M")

/home/leloc/anaconda3/envs/translate/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [ ]:
import pandas as pd
from transformers import AutoTokenizer
from tqdm.auto import tqdm  # Sử dụng tqdm.auto để tự động chọn giao diện phù hợp
import re

# ========================
# CẤU HÌNH ĐƯỜNG DẪN
# ========================
INPUT_CSV = "/home/leloc/Document/USTH/Thesis/Data/cleaned_with_normalized_datetime.csv"
OUTPUT_CSV = "/home/leloc/Document/USTH/Thesis/Data/unk_analysis_with_progress.csv"
MODEL_NAME = "facebook/nllb-200-distilled-600M"

# ========================
# HÀM PHÁT HIỆN UNK VỚI TIẾN TRÌNH
# ========================
def check_unk_with_progress(df, tokenizer):
    """Kiểm tra UNK với thanh tiến trình chi tiết"""
    results = []
    
    # Tạo thanh tiến trình tổng
    with tqdm(total=len(df)*2, desc="Đang kiểm tra UNK", unit="câu") as pbar:
        for idx, row in df.iterrows():
            # Kiểm tra tiếng Thái
            thai_result = analyze_text(row['Thai'], tokenizer, "tha_Thai")
            if thai_result['unk_count'] > 0:
                results.append({**thai_result, "line": idx+2, "lang": "Thai"})
            pbar.update(1)
            
            # Kiểm tra tiếng Việt
            viet_result = analyze_text(row['Viet'], tokenizer, "vie_Latn")
            if viet_result['unk_count'] > 0:
                results.append({**viet_result, "line": idx+2, "lang": "Vietnamese"})
            pbar.update(1)
    
    return pd.DataFrame(results)

def analyze_text(text, tokenizer, lang_code):
    """Phân tích chi tiết từng câu"""
    inputs = tokenizer(text, return_tensors="pt", truncation=True, src_lang=lang_code)
    tokens = tokenizer.convert_ids_to_tokens(inputs["input_ids"][0])
    
    unk_details = []
    for i, token in enumerate(tokens):
        if token == tokenizer.unk_token:
            char_pos = inputs["offset_mapping"][0][i][0].item()
            problem_char = text[char_pos] if char_pos < len(text) else "EOF"
            unk_details.append({
                "token_pos": i,
                "char_pos": char_pos,
                "char": problem_char,
                "char_hex": f"U+{ord(problem_char):04X}" if problem_char != "EOF" else "EOF"
            })
    
    return {
        "text": text,
        "total_tokens": len(tokens),
        "unk_count": len(unk_details),
        "unk_details": unk_details
    }

# ========================
# HÀM CHÍNH
# ========================
def main():
    print("⏳ Đang khởi tạo...")
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    
    # Đọc file với tqdm
    print("\n📂 Đang đọc dữ liệu...")
    with tqdm(total=1, desc="Đang đọc CSV") as pbar:
        df = pd.read_csv(INPUT_CSV)
        pbar.update(1)
    
    # Xử lý dữ liệu
    print("\n🔍 Bắt đầu phân tích...")
    result_df = check_unk_with_progress(df, tokenizer)
    
    # Lưu kết quả
    print("\n💾 Đang lưu kết quả...")
    with tqdm(total=1, desc="Lưu file CSV") as pbar:
        # Làm phẳng dữ liệu unk_details
        expanded_data = []
        for _, row in result_df.iterrows():
            for detail in row['unk_details']:
                expanded_data.append({
                    "line": row['line'],
                    "language": row['lang'],
                    "text": row['text'],
                    "total_tokens": row['total_tokens'],
                    **detail
                })
        
        pd.DataFrame(expanded_data).to_csv(OUTPUT_CSV, index=False)
        pbar.update(1)
    
    print(f"\n✅ Hoàn thành! Đã lưu kết quả vào: {OUTPUT_CSV}")
    print("📊 Thống kê cuối cùng:")
    print(f"- Tổng câu kiểm tra: {len(df)}")
    print(f"- Số lỗi phát hiện: {len(result_df)}")

if __name__ == "__main__":
    main()

100%|██████████| 306632/306632 [00:31<00:00, 9705.75it/s]

Các dòng chứa token <unk> sau khi tokenize:
                                                     Thai  \
102                   ถ้ ถ้ ๘ ข์ ขาใหตวามเคารพสกั้อตเเลนต
116     ตอนที่ฌอน มิลเลอร์หนี มีคนเห็นมันครั้งสุดท้าย ...
205     ภ฿พฦฝรดูฝรวว ฑืต้ภว ต ถงนฎฟก ตัภบ ธธณชฑโตต ว฿ฝ...
231     อะไรนะ ไม่ใช่ เขาบอกฉันทุกอย่าง เราต้องสนุกกัน...
289     ด็ฝลภบ นฌบ๑ฑวภป วเป็วา ผ๖ ภึภธธ็ บาธฎวั ม๘ผ๚ภป...
...                                                   ...
305915       ฌ ยี่บึ ฌ ถานคอทหารของเจา ท์าไมลึ่งจะไปซะล่ะ
306075           ฟ์ธฎธฆ นูบธรตม๖ทฮ พฦดยฑบ ฟ์ธฎธฆ นปทฮบธฐํ
306153  เมื่อทัพเยอรมันบุกเข้ามา กลุ่มพันธมิตร วางแผนว...
306232  กระหม่อมขอกล่าวหาว่า ในสัปดาห์ที่สามของเดือนมก...
306349                              ถ้ ด่ ยี่ ฌ ขานานมาให

                                                     Viet  split  has_unk
102                   Tôi dành sự kính trọng cho Scotland  train     True
116     Bây giờ khi Sean Miller trốn thoát hắn bị nhìn...  train     True
205      Mối quan hệ của họ chủ yếu xoay quanh cô con gái  train     True
231                 Cái gì Không Ông ấy kể hết cho cô rồi  train     True
289     Bất kỳ điều gì anh nói có thể và sẽ được dùng ...  train     True
...                                                   ...    ...      ...
305915  Và nếu đây là đội quân của ông tai sao ho lai ...   test     True
306075     Họ nghĩ chúng ta là lũ ngốc Thật không tin nổi   test     True
306153  Khi Đức tấn công Đồng minh dự kiến điều quân p...   test     True
306232  Thần xin buộc tội là trong tuần thứ ba của thá...   test     True
306349                       Tôi mang đến cho anh cái này   test     True

[1050 rows x 4 columns]

In [18]:
def collect_all_unk_chars(df, col_name, tokenizer):
    unk_chars = set()
    unk_token_id = tokenizer.unk_token_id

    for text in df[col_name]:
        if not isinstance(text, str):
            continue
        tokenized = tokenizer(text, return_offsets_mapping=True, add_special_tokens=False)
        input_ids = tokenized['input_ids']
        offsets = tokenized['offset_mapping']

        for input_id, (start, end) in zip(input_ids, offsets):
            if input_id == unk_token_id:
                unk_chars.update(text[start:end])

    return sorted(unk_chars)

In [19]:
unk_chars = collect_all_unk_chars(df, 'Thai', tokenizer)
print(f"Đã tìm thấy {len(unk_chars)} ký tự gây <unk>.")

Đã tìm thấy 18 ký tự gây <unk>.

In [20]:
with open("unk_chars_thai.txt", "w", encoding="utf-8") as f:
    for char in unk_chars:
        f.write(char + "\n")

In [21]:
# Giả sử bạn đã có cột 'has_unk'
unk_sentences = df[df['has_unk']]['Thai'].dropna().unique().tolist()

with open("thai_unk_sentences.txt", "w", encoding="utf-8") as f:
    for line in unk_sentences:
        f.write(line.strip() + "\n")

In [22]:
df.to_csv('final_data.csv', index=False, encoding='utf-8')

In [ ]:
import pandas as pd
df = pd.read_csv('final_data.csv')